apiVersion: apps/v1
kind: Deployment
metadata:
  name: uvicorn-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uvicorn-app
  template:
    metadata:
      labels:
        app: uvicorn-app
    spec:
      containers:
      - name: uvicorn-app
        image: ntd284/uvicorn-app:v0.2.4 # Ensure the image is valid
        ports:
        - containerPort: 8000  # FastAPI app port
        env:  # Add environment variables here
        - name: QDRANT_HOST
          value: "qdrant-service"  # Qdrant service name in Kubernetes
        - name: QDRANT_PORT
          value: "6333"  # Qdrant port in Kubernetes
        - name: REDIS_HOST
          value: "redis-service"  # Redis service name in Kubernetes
        - name: REDIS_PORT
          value: "6379"  # Redis port in Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: uvicorn-service
spec:
  selector:
    app: uvicorn-app
  ports:
    - protocol: TCP
      port: 8000        # The port that the service listens on
      targetPort: 8000   # The port on the pod that receives traffic
      nodePort: 30080    # External port (must be in the 30000-32767 range)
  type: NodePort