apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uvicorn-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: uvicorn.local  # Update this with your actual domain or IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uvicorn-service
                port:
                  number: 8000
